use_frameworks!

platform :ios, '8.0'

target 'Batch-AtInternet-Dispatcher_Example' do
  pod 'BatchATInternetDispatcher', :path => '../'

  target 'Batch-AtInternet-Dispatcher_Tests' do
    inherit! :search_paths

    pod 'OCMock'
  end
end
